server:
  port: 8085


spring:
  datasource:
    url: jdbc:postgresql://resources:5432/resources
    username: user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

s3.storage.url: http://localstack:4566
#s3.storage.bucket.name: songs-bucket

management.endpoints.web.exposure.include: '*'