scrape_configs:
  - job_name: 'song-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: ['song-service:8081'] ## host and port for your mis
  - job_name: 'resource-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8080']
  - job_name: 'resource-processor'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-processor:8082']      
  - job_name: 'storage-service'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['storage-service:8085']
  - job_name: 'security-server'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['security-server:8008']