spring:
  application.name: resource-processor

  kafka:
    bootstrap-servers: localhost:9092

server.port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: '*'

s3.storage.url=http://localhost:4566
s3.storage.bucket.name=songs-bucket
