spring:
  datasource:
    url: jdbc:postgresql://resources:5432/resources
    username: user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  kafka:
    bootstrap-servers: broker:9092

server.port: 8080

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      internal:
        InstanceMetadataServiceResourceFetcher: error

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

s3.storage.url: http://localstack:4566

storage:
  service:
    url: http://storage-service:8085/storages/type

management.endpoints.web.exposure.include: '*'
management.endpoint.metrics.enabled: true
management.endpoint.prometheus.enabled: true
management.metrics.export.prometheus.enabled: true

