spring:

  kafka:
    bootstrap-servers: broker:9092

server.port: 8082

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      internal:
        InstanceMetadataServiceResourceFetcher: error

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
s3.storage.url: http://localstack:4566
s3.storage.bucket.name: songs-bucket

management.endpoints.web.exposure.include: '*'