spring:
  application.name: resource-processor

  kafka:
    bootstrap-servers: broker:9092

server.port: 8082

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      internal:
        InstanceMetadataServiceResourceFetcher: error

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management.endpoints.web.exposure.include: '*'