spring:
  application.name: song-service

  kafka:
    bootstrap-servers: localhost:9092

server.port: 8081

eureka:
  instance:
#    hostname: search
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management.endpoints.web.exposure.include: '*'
