server:
  port: 8085


spring:
  datasource:
    url: jdbc:postgresql://storages:5432/storages
    username: user
    password: password
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloack:8099/auth/realms/storage-service/protocol/openid-connect/certs
  

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: http://broker:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

s3.storage.url: http://localstack:4566
