spring:
  application:
    name: config-server

  profiles:
    active: local,development,production
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AntonIshchenko/microservice_cource.git
          search-paths: config/
          force-pull: true

server:
  port: 8090
management:
  security:
    enabled: false
