spring:

  kafka:
    bootstrap-servers: localhost:9092

server.port: 8082

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      internal:
        InstanceMetadataServiceResourceFetcher: error

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
s3.storage.url: http://localhost:4566

storage:
  service:
    url: http://localhost:8085/storages/type

management.endpoints.web.exposure.include: '*'