spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/resources
    username: user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  kafka:
    bootstrap-servers: localhost:9092

server.port: 8080

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
      internal:
        InstanceMetadataServiceResourceFetcher: error

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

s3.storage.url: http://localhost:4566

storage:
  service:
    url: http://localhost:8085/storages/type

management.endpoints.web.exposure.include: '*'
